### ISSUE TITLE
Deprecate is.function(lint_message) in xml_nodes_to_lints()

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#1257]
Not really necessary now that `lint_message` accepts vectors -- h/t @AshesITR for the improvement.

PRs for #1199 handled most of the work here; what's left mostly needs some refactoring to get it going (I'll tally a list here once all the #1199 PRs have landed on `main`)

`grep -Fr "lint_message = function" R` gives us these to start:

 - [x] #1289 `yoda_test_linter()`
 - [x] #1291 `seq_linter()`
 - [x] #1294 `unused_import_linter()`
 - [x] #1295 `undesirable_operator_linter()`
 - [x] #1296 `package_hooks_linter()`

**Comment by AshesITR** [comment]
Oh, that's a nicer way to track  the checklists, without creating mini-issues.
