### ISSUE TITLE
Google linters for 3.0.0 release

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/lintr#962]
Splitting off a subset of #884 as a TODO list for 3.0.0 release; the rest of the linters can be done after that.

- [x] `AnyDuplicatedLinter` - Require usage of anyDuplicated() > 0 over any(duplicated(.)) #986
- [x] `AnyIsNALinter` - Require usage of anyNA over any(is.na(.)) #975
- [x] `ClassEqualsLinter` - Block comparison of class with == #989
- [x] ~`StopPasteLinter`~ `condition_message_linter` - Block usage of paste() and paste0() with messaging functions using ... #999
- [x] ~`MultipleStopifnotLinter`~ `ConsecutiveStopifnotLinter` - Force consecutive stopifnot() calls into just one #1005 
- [x] `ElseSameLineLinter` - Require else to come on the same line as the preceding brace #1002
- [x] `ExpectComparisonLinter` - Require usage of expect_gt(x, y) over expect_true(x > y) (and similar) #955 
- [x] `ExpectIdenticalLinter` - Require usage of expect_identical(x, y) where appropriate #958 
- [x] `ExpectIsLinter` - Redirect away from deprecated testthat::expect_is() #946 
- [x] `ExpectLengthLinter` - Require usage of expect_length(x, n) over expect_equal(length(x), n) #950 
- [x] `ExpectNamedLinter` - Require usage of expect_named(x, n) over expect_equal(names(x), n) #949 
- [x] `ExpectNotLinter` - Require usage of expect_false(.) over expect_true(!.) #945 
- [x] `ExpectNullLinter` - Require usage of expect_null(x) over expect_equal(x, NULL) and similar #887 
- [x] `ExpectS3ClassLinter` - Require usage of expect_s3_class() or expect_s4_class() where appropriate. #943
- [x] `ExpectS4ClassLinter` - Require usage of expect_s4_class(x, k) over expect_true(is(x, k)) #943 
- [x] ~`ExpectTrueFalseAndConditionLinter`~ `conjunct_test_linter` - Force && conditions in expect_true(), expect_false() to be written separately #948 
- [x] `ExpectTrueFalseLinter` - Require usage of expect_true(x) over expect_equal(x, TRUE) #947 
- [x] `ExpectTypeLinter` - Require usage of expect_type(x, type) over expect_equal(typeof(x), type) #924 
- [x] `FixedRegexLinter` - Require usage of 'fixed=TRUE' in regular expressions where appropriate #1021 
- [x] `FunctionBraceLinter` - Require multi-line functions to use braces #987
- [x] `IfelseCensorLinter` - Block usage of ifelse where pmin or pmax is more appropriate #1007
- [x] `IfElseMatchBracesLinter` - Require both or neither if/else branches to use curly braces #983
- [x] `InnerCombineLinter` - Require c() to be applied before relatively expensive vectorized functions #1012 
- [x] `LiteralCoercionLinter` - Require usage of correctly-typed literals over literal coercions #995
- [x] `NestedIfelseLinter` - Block usage of nested ifelse() calls #996
- [x] `NumericLeadingZeroLinter` - Require usage of a leading zero in all fractional numerics #992
- [x] `OuterNegationLinter` - Require usage of !any(.) over all(!.), !all(.) over any(!.) #988
- [x] `PasteSepLinter` - Block usage of paste() with sep='' #997 
- [x] `PasteToStringLinter` - Block usage of paste() with collapse=', ' #1013
- [x] `PipeCallLinter` - Force explicit calls in magrittr pipes #801
- [x] `RedundantIfelseLinter` - Prevent ifelse() from being used to produce TRUE/FALSE #1000
- [x] ~`GrepSubsetLinter`~ `RegexSubsetLinter` - Require usage of grep(value = TRUE) over x[grep(x)] #1004
- [x] ~`StopifnotAndConditionLinter`~ `conjunct_test_linter` - Force && conditions in stopifnot() to be written separately #1011
- [x] `StringsAsFactorsLinter` - Identify cases where stringsAsFactors should be supplied explicitly #1020
- [x] `SystemFileLinter` - Block usage of file.path() with system.file() #1006
- [x] `UnreachableCodeLinter` - Block unreachable code and comments following return statements #1003
- [x] `VectorLogicLinter` - Enforce usage of scalar && in conditional statements #978
- [x] `YodaTestLinter` - Block obvious 'yoda tests' #957

**Comment by AshesITR** [comment]
Do we want to expose `google_linters` as an alternative to `default_linters` in 3.0.0, or hold off for now?
NB it would require changing some configuration options for some of the (default) linters IINM, so wouldn't be equivalent to `linters_with_tags("google")`, even if that tag was introduced (which it still should).

**Comment by MichaelChirico** [comment]
my instinct is to hold off for now... want to prioritize 3.0.0 now & don't think it's quite as straightforward to deliver this. want to think a bit more carefully as well as discuss internally what that object should be.
